export type ParkItem = {
  periodTicketAmount: number;
  periodDayTimeAmount: number;
  periodNightAmount: number;
  periodTransTicketAmount: number;
  periodTransDayTimeAmount: number;
  periodTransNightAmount: number;
  gradeInfoList?: unknown;
  periodUseDivisionCode: string;
  periodAllotType: string;
  parkingDivisionCode: string;
  parkingDivisionName: string;
  parkingId: number;
  parkingName: string;
  sectnId: number;
  sectnName: string;
  sectnDescribe: string;
  zipcode: string;
  addr: string;
  addrDetail: string;
  sidoName: string;
  sigunguName: string;
  roadName: string;
  buildingSubNo: string;
  buildingMainNo: string;
  detailBuildingName: string;
  transYn: "Y" | "N";
  bigGradeYn: "Y" | "N";
  baseYn: string;
  muinYn: "Y" | "N";
  simpleSettingYn: "Y" | "N";
  extraParkingYn: "Y" | "N";
  periodOpenYn: "Y" | "N";
  anyhourRunYn: "Y" | "N";
  currentPeriodWaitingCount: number;
  lat: string;
  lng: string;
  periodType: string;
  telNo: string;
  cellCount: number;
  handicapCellCount: number;
  smallCarCellCount: number;
  electricCellCount: number;
  elderlyCellCount: number;
  womanFirstCellCount: number;
  periodCellCount: number;
  parkCount: number;
  quarter: number;
  usingMonth: number;
};
