export type GradeAmount = {
  gradeAmountId: number;
  gradeInfoName: string;
  revision: number;
  turnTime: number;
  freeTime: number;
  defaultTime: number;
  defaultAmount: number;
  intervalTime: number;
  intervalAmount: number;
  employeeAmount: number;
  eventAmount: number;
  dayParkingAmount: number;
  periodTicketAmount: number;
  periodDayTimeAmount: number;
  periodNightAmount: number;
  periodTransTicketAmount: number;
  periodTransDayTimeAmount: number;
  periodTransNightAmount: number;
  periodSecondAmount: number;
};

export type GradeInfo = {
  dayType: "WEEK" | "SAT" | "SUN" | "HOLI";
  gradeAmountId: number;
  gradeBigId: number;
  gradeNightId: number;
  gradePeakId: number;
  parkingId: number;
  simpleYn: "Y" | "N";
  startTime: string | null;
  endTime: string | null;
  gradeAmount: GradeAmount;
  bigGradeAmount: GradeAmount;
  nightGradeAmount: GradeAmount;
  peakGradeAmount: GradeAmount;
};

export type ParkItem = {
  periodTicketAmount: number;
  periodDayTimeAmount: number;
  periodNightAmount: number;
  periodTransTicketAmount: number;
  periodTransDayTimeAmount: number;
  periodTransNightAmount: number;
  gradeInfoList: GradeInfo[];
  periodUseDivisionCode: string;
  periodAllotType: string;
  parkingDivisionCode: string;
  parkingDivisionName: string;
  parkingId: number;
  parkingName: string;
  sectnId: number;
  sectnName: string;
  sectnDescribe: string;
  zipcode: string;
  addr: string;
  addrDetail: string;
  sidoName: string;
  sigunguName: string;
  roadName: string;
  buildingSubNo: string;
  buildingMainNo: string;
  detailBuildingName: string;
  transYn: "Y" | "N";
  bigGradeYn: "Y" | "N";
  baseYn: string;
  muinYn: "Y" | "N";
  simpleSettingYn: "Y" | "N";
  extraParkingYn: "Y" | "N";
  periodOpenYn: "Y" | "N";
  anyhourRunYn: "Y" | "N";
  currentPeriodWaitingCount: number;
  lat: string;
  lng: string;
  periodType: string;
  telNo: string;
  cellCount: number;
  handicapCellCount: number;
  smallCarCellCount: number;
  electricCellCount: number;
  elderlyCellCount: number;
  womanFirstCellCount: number;
  periodCellCount: number;
  parkCount: number;
  quarter: number;
  usingMonth: number;
};
